// Generated by CoffeeScript 1.6.2
var Tana;

Tana = (function() {
  function Tana(prices) {
    this.prices = prices;
  }

  Tana.prototype.SMA = function(peroid) {
    var avg, i, sma, _i, _j, _k, _ref, _ref1;

    if (peroid == null) {
      peroid = 5;
    }
    if (!((1 <= peroid && peroid <= this.prices.length))) {
      return void 0;
    }
    sma = [];
    for (i = _i = 0, _ref = peroid - 1; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      sma.push(void 0);
    }
    avg = 0;
    for (i = _j = 0; 0 <= peroid ? _j < peroid : _j > peroid; i = 0 <= peroid ? ++_j : --_j) {
      avg += this.prices[i];
    }
    avg /= peroid;
    sma.push(avg);
    for (i = _k = peroid, _ref1 = this.prices.length; peroid <= _ref1 ? _k < _ref1 : _k > _ref1; i = peroid <= _ref1 ? ++_k : --_k) {
      avg += (this.prices[i] - this.prices[i - peroid]) / peroid;
      sma.push(Math.round(avg * 1000) / 1000);
    }
    return sma;
  };

  Tana.prototype.EMA = function(peroid) {
    var alpha, element, ema, i, _i, _j, _len, _ref, _results;

    if (peroid === void 0) {
      peroid = this.prices.length;
    }
    if (!((1 <= peroid && peroid <= this.prices.length))) {
      return void 0;
    }
    ema = [];
    ema.push(this.prices[0]);
    alpha = 2 / (peroid + 1);
    for (i = _i = 1, _ref = this.prices.length; 1 <= _ref ? _i < _ref : _i > _ref; i = 1 <= _ref ? ++_i : --_i) {
      ema.push(ema[i - 1] + alpha * (this.prices[i] - ema[i - 1]));
    }
    _results = [];
    for (_j = 0, _len = ema.length; _j < _len; _j++) {
      element = ema[_j];
      _results.push(Math.round(element * 1000) / 1000);
    }
    return _results;
  };

  return Tana;

})();
