// Generated by CoffeeScript 1.6.2
describe('SMA', function() {
  var prices, tana;

  prices = [];
  tana = null;
  beforeEach(function() {
    prices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    return tana = new Tana(prices);
  });
  it('has method SMA', function() {
    return expect(tana.SMA).toBeDefined();
  });
  it('has default value { peroid: 5 }', function() {
    return expect(tana.SMA()).toEqual(tana.SMA(5));
  });
  it('answers with given peroid from 1 to LENGTH_OF_PRICES', function() {
    expect(tana.SMA(1)).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
    expect(tana.SMA(2)).toEqual([void 0, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5]);
    return expect(tana.SMA(prices.length)).toEqual([void 0, void 0, void 0, void 0, void 0, void 0, void 0, void 0, void 0, 4.5]);
  });
  return it('returns undefined when peroid is out of range', function() {
    expect(tana.SMA(-1)).toBeUndefined();
    expect(tana.SMA(0)).toBeUndefined();
    return expect(tana.SMA(20)).toBeUndefined();
  });
});

describe('EMA', function() {
  var prices, tana;

  prices = [];
  tana = null;
  beforeEach(function() {
    prices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    return tana = new Tana(prices);
  });
  it('has method EMA', function() {
    return expect(tana.EMA).toBeDefined();
  });
  it('has default value { peroid: LENGTH_OF_PRICES }', function() {
    return expect(tana.EMA()).toEqual(tana.EMA(prices.length));
  });
  it('answers with given peroid from 1 to LENGTH_OF_PRICES', function() {
    expect(tana.EMA(1)).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
    expect(tana.EMA(5)).toEqual([0, 0.333, 0.889, 1.593, 2.395, 3.263, 4.176, 5.117, 6.078, 7.052]);
    return expect(tana.EMA(prices.length)).toEqual([0, 0.182, 0.512, 0.965, 1.517, 2.150, 2.850, 3.604, 4.404, 5.239]);
  });
  return it('returns undefined when peroid is out of range', function() {
    expect(tana.EMA(-1)).toBeUndefined();
    expect(tana.EMA(0)).toBeUndefined();
    return expect(tana.EMA(20)).toBeUndefined();
  });
});
